### ISSUE TITLE
jb build . fails with the following error

### ISSUE THREAD

**Issue by manivmtc** [So-Cool/you-only-write-thrice#1]
Hi thanks for your nice work. However, I tried to follow your README and received the below error on `jb build .`
Update: Issue occurs in python3.9, but diasppears with python3.6

```
(youonlywrite3ce) ➜  you-only-write-thrice git:(master) jb build .
Running Jupyter-Book v0.13.1
Source Folder: /mnt/Drive2TB/m/Work/you-only-write-thrice
Config Path: /mnt/Drive2TB/m/Work/you-only-write-thrice/_config.yml
Output Path: /mnt/Drive2TB/m/Work/you-only-write-thrice/_build/html
Running Sphinx v4.5.0

Extension error:
Could not import extension bibtex_iclr (exception: cannot import name 'BaseReferenceText' from 'sphinxcontrib.bibtex.style.referencing' (/home/m/.miniconda3/envs/youonlywrite3ce/lib/python3.9/site-packages/sphinxcontrib/bibtex/style/referencing/__init__.py))
Traceback (most recent call last):
  File "/home/m/.miniconda3/envs/youonlywrite3ce/lib/python3.9/site-packages/sphinx/registry.py", line 425, in load_extension
    mod = import_module(extname)
  File "/home/m/.miniconda3/envs/youonlywrite3ce/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/mnt/Drive2TB/m/Work/you-only-write-thrice/_ext/bibtex_iclr.py", line 13, in <module>
    from sphinxcontrib.bibtex.style.referencing import BaseReferenceText
ImportError: cannot import name 'BaseReferenceText' from 'sphinxcontrib.bibtex.style.referencing' (/home/m/.miniconda3/envs/youonlywrite3ce/lib/python3.9/site-packages/sphinxcontrib/bibtex/style/referencing/__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/m/.miniconda3/envs/youonlywrite3ce/lib/python3.9/site-packages/jupyter_book/sphinx.py", line 114, in build_sphinx
    app = Sphinx(
  File "/home/m/.miniconda3/envs/youonlywrite3ce/lib/python3.9/site-packages/sphinx/application.py", line 223, in __init__
    self.setup_extension(extension)
  File "/home/m/.miniconda3/envs/youonlywrite3ce/lib/python3.9/site-packages/sphinx/application.py", line 380, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/m/.miniconda3/envs/youonlywrite3ce/lib/python3.9/site-packages/sphinx/registry.py", line 428, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname,
sphinx.errors.ExtensionError: Could not import extension bibtex_iclr (exception: cannot import name 'BaseReferenceText' from 'sphinxcontrib.bibtex.style.referencing' (/home/m/.miniconda3/envs/youonlywrite3ce/lib/python3.9/site-packages/sphinxcontrib/bibtex/style/referencing/__init__.py))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/m/.miniconda3/envs/youonlywrite3ce/bin/jb", line 8, in <module>
    sys.exit(main())
  File "/home/m/.miniconda3/envs/youonlywrite3ce/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/m/.miniconda3/envs/youonlywrite3ce/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/m/.miniconda3/envs/youonlywrite3ce/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/m/.miniconda3/envs/youonlywrite3ce/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/m/.miniconda3/envs/youonlywrite3ce/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/m/.miniconda3/envs/youonlywrite3ce/lib/python3.9/site-packages/jupyter_book/cli/main.py", line 323, in build
    builder_specific_actions(
  File "/home/m/.miniconda3/envs/youonlywrite3ce/lib/python3.9/site-packages/jupyter_book/cli/main.py", line 531, in builder_specific_actions
    raise RuntimeError(_message_box(msg, color="red", doprint=False)) from result
RuntimeError:
===============================================================================

There was an error in building your book. Look above for the cause.

===============================================================================

```

**Comment by So-Cool** [comment]
It appears that the custom BibTeX extension was not loaded. Do you have the `_ext` folder in your root directory and does it contain the `bibtex_iclr.py` file?

**Comment by manivmtc** [comment]
> It appears that the custom BibTeX extension was not loaded. Do you have the `_ext` folder in your root directory and does it contain the `bibtex_iclr.py` file?

Yes `_ext` has the `bibtex_iclr.py` file

**Comment by So-Cool** [comment]
The latest commit ([757f8e5](https://github.com/So-Cool/you-only-write-thrice/commit/757f8e530ed97ec666e9b5265b0246c495411086)) fixes the issue with custom bibliography style.
